name: CI/CD Docker Build & Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: hashinie
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend Docker image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/medi-backend:latest -f backend/Dockerfile ./backend

      - name: Build frontend Docker image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/medi-frontend:latest -f frontend/Dockerfile ./frontend

      - name: Push backend image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/medi-backend:latest

      - name: Push frontend image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/medi-frontend:latest

      - name: Docker system prune
        run: docker system prune -af || true

      - name: Copy deploy script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./deploy_on_ec2.sh
          target: /home/ubuntu/
          overwrite: true

      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ubuntu/deploy_on_ec2.sh
            /home/ubuntu/deploy_on_ec2.sh

